# Generated by Django 4.0.6 on 2022-07-20 06:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='body'),
        ),
    ]
