# Generated by Django 4.0.6 on 2022-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brandmodel_colormodel_sizemodel_productmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
    ]
